#include<stdio.h>
#include<conio.h>
main()
{
	printf("welcome");
	printf("\n");
	printf(2+"welcome");
	printf("\n");
	printf("welcome"+3);
	printf("\n");
	printf(2+"welcome"+3);
	getch();
}
